-- MySQL Script generated by MySQL Workbench
-- Mon Jan  9 15:57:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema univeristy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema univeristy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `univeristy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `univeristy` ;

-- -----------------------------------------------------
-- Table `univeristy`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`club` (
  `clubId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `studentId` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`clubId`),
  UNIQUE INDEX `clubId_UNIQUE` (`clubId` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`students` (
  `id` VARCHAR(11) NOT NULL,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(11) NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`clubstudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`clubstudents` (
  `clubId` INT NOT NULL,
  `studentId` VARCHAR(11) NOT NULL,
  INDEX `clubId_idx` (`clubId` ASC) VISIBLE,
  INDEX `studentId_idx` (`studentId` ASC) VISIBLE,
  CONSTRAINT `studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `univeristy`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clubId`
    FOREIGN KEY (`clubId`)
    REFERENCES `univeristy`.`club` (`clubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`employees` (
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `mobileNumber` VARCHAR(11) NOT NULL,
  `id` VARCHAR(11) NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mobileNumber_UNIQUE` (`mobileNumber` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`courses` (
  `courseId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `credits` INT NOT NULL,
  `studentId` VARCHAR(11) NOT NULL,
  `grade` INT NULL DEFAULT NULL,
  `lecturerId` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`courseId`),
  UNIQUE INDEX `courseId_UNIQUE` (`courseId` ASC) VISIBLE,
  INDEX `lecturerId_idx` (`lecturerId` ASC) VISIBLE,
  CONSTRAINT `lecturerId`
    FOREIGN KEY (`lecturerId`)
    REFERENCES `univeristy`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`coursesstudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`coursesstudents` (
  `courseId` INT NOT NULL,
  `studentId` VARCHAR(11) NOT NULL,
  INDEX `studentId_idx` (`studentId` ASC) VISIBLE,
  CONSTRAINT `studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `univeristy`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `courseId`
    FOREIGN KEY (`courseId`)
    REFERENCES `univeristy`.`courses` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`events` (
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  `eventId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`eventId`),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE,
  UNIQUE INDEX `eventId_UNIQUE` (`eventId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`eventsstudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`eventsstudents` (
  `studentId` VARCHAR(11) NOT NULL,
  `eventId` INT NOT NULL,
  INDEX `studentId_idx` (`studentId` ASC) VISIBLE,
  INDEX `eventId_idx` (`eventId` ASC) VISIBLE,
  CONSTRAINT `studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `univeristy`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `eventId`
    FOREIGN KEY (`eventId`)
    REFERENCES `univeristy`.`events` (`eventId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`finances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`finances` (
  `studentId` VARCHAR(11) NULL DEFAULT NULL,
  `dept` DOUBLE NULL DEFAULT NULL,
  `financeId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`financeId`),
  UNIQUE INDEX `financeId_UNIQUE` (`financeId` ASC) VISIBLE,
  INDEX `studentId_idx` (`studentId` ASC) VISIBLE,
  CONSTRAINT `studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `univeristy`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`scholarships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`scholarships` (
  `name` VARCHAR(255) NOT NULL,
  `coverage` DOUBLE NOT NULL,
  `studentId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `studentId_UNIQUE` (`studentId` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `studentId`
    FOREIGN KEY (`name`)
    REFERENCES `univeristy`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`socialprograms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`socialprograms` (
  `programId` INT NOT NULL AUTO_INCREMENT,
  `studentId` VARCHAR(11) NULL DEFAULT NULL,
  `coverage` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`programId`),
  UNIQUE INDEX `programId_UNIQUE` (`programId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `univeristy`.`studentssocialprograms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univeristy`.`studentssocialprograms` (
  `programId` INT NULL DEFAULT NULL,
  `studentId` VARCHAR(11) NULL DEFAULT NULL,
  INDEX `programId_idx` (`programId` ASC) VISIBLE,
  INDEX `studentId_idx` (`studentId` ASC) VISIBLE,
  CONSTRAINT `studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `univeristy`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `programId`
    FOREIGN KEY (`programId`)
    REFERENCES `univeristy`.`socialprograms` (`programId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
