-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 22:18:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` DEFAULT CHARACTER SET utf8mb3 ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `head_of_department_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`department_id`),
  UNIQUE INDEX `department_id_UNIQUE` (`department_id` ASC) VISIBLE,
  UNIQUE INDEX `head_of_department_id_UNIQUE` (`head_of_department_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`Administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Administration` (
  `employee_id` VARCHAR(11) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL DEFAULT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) VISIBLE,
  INDEX `department_id_for_administration_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `department_id_for_administration`
    FOREIGN KEY (`department_id`)
    REFERENCES `university`.`Departments` (`department_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Students` (
  `student_id` VARCHAR(11) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `photo` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  `birth_date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `student_id_UNIQUE` (`student_id` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Classes` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `level` VARCHAR(45) NOT NULL,
  `department_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`class_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`class_id` ASC) VISIBLE,
  UNIQUE INDEX `department_id_UNIQUE` (`department_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `university`.`Students` (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`Lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Lecturer` (
  `lecturer_id` VARCHAR(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `birth_date` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lecturer_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`lecturer_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`ClassesLecturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`ClassesLecturers` (
  `lecturer_id` VARCHAR(11) NOT NULL,
  `class_id` INT NOT NULL,
  INDEX `fk_class_id_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_class_id_for_lecturer_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_lecturer_id_for_class_idx` (`lecturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_id_for_lecturer`
    FOREIGN KEY (`class_id`)
    REFERENCES `university`.`Classes` (`class_id`),
  CONSTRAINT `fk_lecturer_id_for_class`
    FOREIGN KEY (`lecturer_id`)
    REFERENCES `university`.`Lecturer` (`lecturer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`ClassesStudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`ClassesStudents` (
  `student_id` VARCHAR(11) NOT NULL,
  `class_id` INT NOT NULL,
  INDEX `fk_student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_class_id_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `university`.`Classes` (`class_id`),
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `university`.`Students` (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `organiser_id` VARCHAR(11) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE,
  INDEX `student_id_for_events_idx` (`organiser_id` ASC) VISIBLE,
  CONSTRAINT `student_id_for_events`
    FOREIGN KEY (`organiser_id`)
    REFERENCES `university`.`Students` (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`Finances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Finances` (
  `finance_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `payment_date` DATETIME NOT NULL,
  `student_id` VARCHAR(11) NULL DEFAULT NULL,
  `department_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`finance_id`),
  UNIQUE INDEX `finance_id_UNIQUE` (`finance_id` ASC) VISIBLE,
  UNIQUE INDEX `payment_date_UNIQUE` (`payment_date` ASC) VISIBLE,
  INDEX `fk_student_id_for_finances_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_department_id_for_finances_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_id_for_finances`
    FOREIGN KEY (`department_id`)
    REFERENCES `university`.`Departments` (`department_id`),
  CONSTRAINT `fk_student_id_for_finances`
    FOREIGN KEY (`student_id`)
    REFERENCES `university`.`Students` (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`Scholarships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`Scholarships` (
  `scholarship_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `coverage` DOUBLE NOT NULL,
  PRIMARY KEY (`scholarship_id`),
  UNIQUE INDEX `scholarship_id_UNIQUE` (`scholarship_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`ScholarshipsStudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`ScholarshipsStudents` (
  `scholarship_id` INT NOT NULL,
  `student_id` VARCHAR(11) NOT NULL,
  INDEX `scholarship_id_for_students_idx` (`student_id` ASC) VISIBLE,
  INDEX `student_id_for_scholarship_idx` (`scholarship_id` ASC) VISIBLE,
  CONSTRAINT `scholarship_id_for_students`
    FOREIGN KEY (`student_id`)
    REFERENCES `university`.`Students` (`student_id`),
  CONSTRAINT `student_id_for_scholarship`
    FOREIGN KEY (`scholarship_id`)
    REFERENCES `university`.`Scholarships` (`scholarship_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`SocialPrograms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`SocialPrograms` (
  `social_program_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `coverage` DOUBLE NOT NULL,
  PRIMARY KEY (`social_program_id`),
  UNIQUE INDEX `social_program_id_UNIQUE` (`social_program_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `university`.`SocialProgramsStudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`SocialProgramsStudents` (
  `social_program_id` INT NOT NULL,
  `student_id` VARCHAR(11) NOT NULL,
  INDEX `social_program_id_for_students_idx` (`social_program_id` ASC) VISIBLE,
  INDEX `student_id_for_social_programs_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `social_program_id_for_students`
    FOREIGN KEY (`social_program_id`)
    REFERENCES `university`.`SocialPrograms` (`social_program_id`),
  CONSTRAINT `student_id_for_social_programs`
    FOREIGN KEY (`student_id`)
    REFERENCES `university`.`Students` (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
